// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signal.proto

package com.tradery.grpc.stubs;

public final class SignalOuterClass {
  private SignalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SignalRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.SignalRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string modelName = 1;</code>
     */
    java.lang.String getModelName();
    /**
     * <code>string modelName = 1;</code>
     */
    com.google.protobuf.ByteString
        getModelNameBytes();

    /**
     * <code>string tickerSymbol = 2;</code>
     */
    java.lang.String getTickerSymbol();
    /**
     * <code>string tickerSymbol = 2;</code>
     */
    com.google.protobuf.ByteString
        getTickerSymbolBytes();

    /**
     * <code>string strategy = 3;</code>
     */
    java.lang.String getStrategy();
    /**
     * <code>string strategy = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrategyBytes();
  }
  /**
   * <pre>
   * Define the SignalRequest message containing input parameters.
   * </pre>
   *
   * Protobuf type {@code signalservice.SignalRequest}
   */
  public  static final class SignalRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.SignalRequest)
      SignalRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignalRequest.newBuilder() to construct.
    private SignalRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignalRequest() {
      modelName_ = "";
      tickerSymbol_ = "";
      strategy_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignalRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              modelName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tickerSymbol_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              strategy_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.class, com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.Builder.class);
    }

    public static final int MODELNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object modelName_;
    /**
     * <code>string modelName = 1;</code>
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      }
    }
    /**
     * <code>string modelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TICKERSYMBOL_FIELD_NUMBER = 2;
    private volatile java.lang.Object tickerSymbol_;
    /**
     * <code>string tickerSymbol = 2;</code>
     */
    public java.lang.String getTickerSymbol() {
      java.lang.Object ref = tickerSymbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tickerSymbol_ = s;
        return s;
      }
    }
    /**
     * <code>string tickerSymbol = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTickerSymbolBytes() {
      java.lang.Object ref = tickerSymbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tickerSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRATEGY_FIELD_NUMBER = 3;
    private volatile java.lang.Object strategy_;
    /**
     * <code>string strategy = 3;</code>
     */
    public java.lang.String getStrategy() {
      java.lang.Object ref = strategy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strategy_ = s;
        return s;
      }
    }
    /**
     * <code>string strategy = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrategyBytes() {
      java.lang.Object ref = strategy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getModelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modelName_);
      }
      if (!getTickerSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tickerSymbol_);
      }
      if (!getStrategyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, strategy_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getModelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modelName_);
      }
      if (!getTickerSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tickerSymbol_);
      }
      if (!getStrategyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, strategy_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tradery.grpc.stubs.SignalOuterClass.SignalRequest)) {
        return super.equals(obj);
      }
      com.tradery.grpc.stubs.SignalOuterClass.SignalRequest other = (com.tradery.grpc.stubs.SignalOuterClass.SignalRequest) obj;

      boolean result = true;
      result = result && getModelName()
          .equals(other.getModelName());
      result = result && getTickerSymbol()
          .equals(other.getTickerSymbol());
      result = result && getStrategy()
          .equals(other.getStrategy());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODELNAME_FIELD_NUMBER;
      hash = (53 * hash) + getModelName().hashCode();
      hash = (37 * hash) + TICKERSYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getTickerSymbol().hashCode();
      hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
      hash = (53 * hash) + getStrategy().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tradery.grpc.stubs.SignalOuterClass.SignalRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the SignalRequest message containing input parameters.
     * </pre>
     *
     * Protobuf type {@code signalservice.SignalRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.SignalRequest)
        com.tradery.grpc.stubs.SignalOuterClass.SignalRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.class, com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.Builder.class);
      }

      // Construct using com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        modelName_ = "";

        tickerSymbol_ = "";

        strategy_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalRequest_descriptor;
      }

      @java.lang.Override
      public com.tradery.grpc.stubs.SignalOuterClass.SignalRequest getDefaultInstanceForType() {
        return com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tradery.grpc.stubs.SignalOuterClass.SignalRequest build() {
        com.tradery.grpc.stubs.SignalOuterClass.SignalRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tradery.grpc.stubs.SignalOuterClass.SignalRequest buildPartial() {
        com.tradery.grpc.stubs.SignalOuterClass.SignalRequest result = new com.tradery.grpc.stubs.SignalOuterClass.SignalRequest(this);
        result.modelName_ = modelName_;
        result.tickerSymbol_ = tickerSymbol_;
        result.strategy_ = strategy_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tradery.grpc.stubs.SignalOuterClass.SignalRequest) {
          return mergeFrom((com.tradery.grpc.stubs.SignalOuterClass.SignalRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tradery.grpc.stubs.SignalOuterClass.SignalRequest other) {
        if (other == com.tradery.grpc.stubs.SignalOuterClass.SignalRequest.getDefaultInstance()) return this;
        if (!other.getModelName().isEmpty()) {
          modelName_ = other.modelName_;
          onChanged();
        }
        if (!other.getTickerSymbol().isEmpty()) {
          tickerSymbol_ = other.tickerSymbol_;
          onChanged();
        }
        if (!other.getStrategy().isEmpty()) {
          strategy_ = other.strategy_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tradery.grpc.stubs.SignalOuterClass.SignalRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tradery.grpc.stubs.SignalOuterClass.SignalRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object modelName_ = "";
      /**
       * <code>string modelName = 1;</code>
       */
      public java.lang.String getModelName() {
        java.lang.Object ref = modelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          modelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string modelName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getModelNameBytes() {
        java.lang.Object ref = modelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string modelName = 1;</code>
       */
      public Builder setModelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string modelName = 1;</code>
       */
      public Builder clearModelName() {
        
        modelName_ = getDefaultInstance().getModelName();
        onChanged();
        return this;
      }
      /**
       * <code>string modelName = 1;</code>
       */
      public Builder setModelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        modelName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tickerSymbol_ = "";
      /**
       * <code>string tickerSymbol = 2;</code>
       */
      public java.lang.String getTickerSymbol() {
        java.lang.Object ref = tickerSymbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tickerSymbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tickerSymbol = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTickerSymbolBytes() {
        java.lang.Object ref = tickerSymbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tickerSymbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tickerSymbol = 2;</code>
       */
      public Builder setTickerSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tickerSymbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tickerSymbol = 2;</code>
       */
      public Builder clearTickerSymbol() {
        
        tickerSymbol_ = getDefaultInstance().getTickerSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string tickerSymbol = 2;</code>
       */
      public Builder setTickerSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tickerSymbol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object strategy_ = "";
      /**
       * <code>string strategy = 3;</code>
       */
      public java.lang.String getStrategy() {
        java.lang.Object ref = strategy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strategy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string strategy = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrategyBytes() {
        java.lang.Object ref = strategy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strategy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strategy = 3;</code>
       */
      public Builder setStrategy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strategy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string strategy = 3;</code>
       */
      public Builder clearStrategy() {
        
        strategy_ = getDefaultInstance().getStrategy();
        onChanged();
        return this;
      }
      /**
       * <code>string strategy = 3;</code>
       */
      public Builder setStrategyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strategy_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.SignalRequest)
    }

    // @@protoc_insertion_point(class_scope:signalservice.SignalRequest)
    private static final com.tradery.grpc.stubs.SignalOuterClass.SignalRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tradery.grpc.stubs.SignalOuterClass.SignalRequest();
    }

    public static com.tradery.grpc.stubs.SignalOuterClass.SignalRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignalRequest>
        PARSER = new com.google.protobuf.AbstractParser<SignalRequest>() {
      @java.lang.Override
      public SignalRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignalRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignalRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignalRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tradery.grpc.stubs.SignalOuterClass.SignalRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignalResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.SignalResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 signal = 1;</code>
     */
    int getSignal();
  }
  /**
   * <pre>
   * Define the SignalResponse message containing the numeric signal.
   * </pre>
   *
   * Protobuf type {@code signalservice.SignalResponse}
   */
  public  static final class SignalResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.SignalResponse)
      SignalResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignalResponse.newBuilder() to construct.
    private SignalResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignalResponse() {
      signal_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignalResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              signal_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.class, com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.Builder.class);
    }

    public static final int SIGNAL_FIELD_NUMBER = 1;
    private int signal_;
    /**
     * <code>int32 signal = 1;</code>
     */
    public int getSignal() {
      return signal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signal_ != 0) {
        output.writeInt32(1, signal_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tradery.grpc.stubs.SignalOuterClass.SignalResponse)) {
        return super.equals(obj);
      }
      com.tradery.grpc.stubs.SignalOuterClass.SignalResponse other = (com.tradery.grpc.stubs.SignalOuterClass.SignalResponse) obj;

      boolean result = true;
      result = result && (getSignal()
          == other.getSignal());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
      hash = (53 * hash) + getSignal();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tradery.grpc.stubs.SignalOuterClass.SignalResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the SignalResponse message containing the numeric signal.
     * </pre>
     *
     * Protobuf type {@code signalservice.SignalResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.SignalResponse)
        com.tradery.grpc.stubs.SignalOuterClass.SignalResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.class, com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.Builder.class);
      }

      // Construct using com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signal_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tradery.grpc.stubs.SignalOuterClass.internal_static_signalservice_SignalResponse_descriptor;
      }

      @java.lang.Override
      public com.tradery.grpc.stubs.SignalOuterClass.SignalResponse getDefaultInstanceForType() {
        return com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tradery.grpc.stubs.SignalOuterClass.SignalResponse build() {
        com.tradery.grpc.stubs.SignalOuterClass.SignalResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tradery.grpc.stubs.SignalOuterClass.SignalResponse buildPartial() {
        com.tradery.grpc.stubs.SignalOuterClass.SignalResponse result = new com.tradery.grpc.stubs.SignalOuterClass.SignalResponse(this);
        result.signal_ = signal_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tradery.grpc.stubs.SignalOuterClass.SignalResponse) {
          return mergeFrom((com.tradery.grpc.stubs.SignalOuterClass.SignalResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tradery.grpc.stubs.SignalOuterClass.SignalResponse other) {
        if (other == com.tradery.grpc.stubs.SignalOuterClass.SignalResponse.getDefaultInstance()) return this;
        if (other.getSignal() != 0) {
          setSignal(other.getSignal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tradery.grpc.stubs.SignalOuterClass.SignalResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tradery.grpc.stubs.SignalOuterClass.SignalResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int signal_ ;
      /**
       * <code>int32 signal = 1;</code>
       */
      public int getSignal() {
        return signal_;
      }
      /**
       * <code>int32 signal = 1;</code>
       */
      public Builder setSignal(int value) {
        
        signal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 signal = 1;</code>
       */
      public Builder clearSignal() {
        
        signal_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.SignalResponse)
    }

    // @@protoc_insertion_point(class_scope:signalservice.SignalResponse)
    private static final com.tradery.grpc.stubs.SignalOuterClass.SignalResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tradery.grpc.stubs.SignalOuterClass.SignalResponse();
    }

    public static com.tradery.grpc.stubs.SignalOuterClass.SignalResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignalResponse>
        PARSER = new com.google.protobuf.AbstractParser<SignalResponse>() {
      @java.lang.Override
      public SignalResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignalResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignalResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignalResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tradery.grpc.stubs.SignalOuterClass.SignalResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_SignalRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_SignalRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_SignalResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_SignalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014signal.proto\022\rsignalservice\"J\n\rSignalR" +
      "equest\022\021\n\tmodelName\030\001 \001(\t\022\024\n\014tickerSymbo" +
      "l\030\002 \001(\t\022\020\n\010strategy\030\003 \001(\t\" \n\016SignalRespo" +
      "nse\022\016\n\006signal\030\001 \001(\0052R\n\006Signal\022H\n\tGetSign" +
      "al\022\034.signalservice.SignalRequest\032\035.signa" +
      "lservice.SignalResponseB\030\n\026com.tradery.g" +
      "rpc.stubsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_signalservice_SignalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signalservice_SignalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_SignalRequest_descriptor,
        new java.lang.String[] { "ModelName", "TickerSymbol", "Strategy", });
    internal_static_signalservice_SignalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_signalservice_SignalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_SignalResponse_descriptor,
        new java.lang.String[] { "Signal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
